### ISSUE TITLE
Testing on Windows Server 2008R2

### ISSUE THREAD

**Issue by fujimotos** [fluent-plugins-nursery/fluent-plugin-sigdump#1]
**TODO**

* Launch Windows Server 2008R2 machine using Azure
* Confirm that this plugin works on that platform

@daipom  I'm going to check this this evening.

**Comment by fujimotos** [comment]
I tested this plugin on Windows Server 2008R2 (based on c71bba9178107c877dfaa46953e063361ec87409).

It worked. Here is the screenshot taken during the testing:

**Screenshot**
![win2008R2](https://user-images.githubusercontent.com/8974561/154876332-fb369b03-ddcf-42b3-9096-e9fd527f9bcf.png)

**Comment by daipom** [comment]
Thanks!

**Comment by fujimotos** [comment]
Addendum: The TD Agent version used in this testing was `td-agent-4.3.0-x64.msi`.
