### ISSUE TITLE
Submit to RubyGems.org

### ISSUE THREAD

**Issue by daipom** [fluent-plugins-nursery/fluent-plugin-sigdump#4]
- [x] Release v1.0.0 on GitHub
- [x] Push gem to RubyGems.org
- [x] Adjust the owners

**Comment by fujimotos** [comment]
Now, go for it!

**Comment by daipom** [comment]
All done!
And I have confirmed I can install the gem and it works correctly.

```console
$ gem install fluent-plugin-sigdump 
```

**Comment by daipom** [comment]
gem: https://rubygems.org/gems/fluent-plugin-sigdump

**Comment by fujimotos** [comment]
@daipom Thank you!
